FossifyOrg/Calendar

app/src/main/kotlin/org/fossify/calendar/fragments/MonthDayFragment.kt

There is a bug that event markers on Monthly and daily view are not removed after removing an event. Here's the original bug report from SMT:
> If a given days events are deleted by long pressing an event and using Delete at the top menu and the given day no longer contains events, the dots under date should be removed too.
This PR fixes that issue.
**Before:**
https://github.com/FossifyOrg/Calendar/assets/85929121/288dcabe-f89c-4380-b055-8091fee0f5ad
**After:**
https://github.com/FossifyOrg/Calendar/assets/85929121/3c27cd6d-dce1-475f-8dd5-d95db83f827b

Fixed refreshing day event dots

---

.github/ISSUE_TEMPLATE/bug_report.md

Clarifies the issue template in the same way as in my first PR in the gallery repo ([#64](https://github.com/FossifyOrg/Gallery/pull/64)).

Clarify the issue template (Calendar)

---

app/src/main/kotlin/org/fossify/calendar/activities/EventActivity.kt
app/src/main/kotlin/org/fossify/calendar/activities/TaskActivity.kt
app/src/main/kotlin/org/fossify/calendar/dialogs/RepeatRuleWeeklyDialog.kt
app/src/main/kotlin/org/fossify/calendar/extensions/Long.kt
app/src/main/kotlin/org/fossify/calendar/helpers/Parser.kt

It is very roundabout way to use Math.pow to bitshift integer.

Use bitshift operator instead of Math.pow

---

app/src/main/kotlin/org/fossify/calendar/views/MonthViewWrapper.kt

- The problem was that the screen width is exactly divisible by 7 (the number of days in one row/week), so in line 77 (where it was `<` instead of `<=`) it instead wrapped the last element always to the next line.
https://github.com/FossifyOrg/Calendar/blob/abd573cc43dacb5320eb09a35ae94ffad821b237/app/src/main/kotlin/org/fossify/calendar/views/MonthViewWrapper.kt#L77
- Removed redundant position calculations, as they are instantly altered by the onLayout function, so they are not even used. (can be reverted if not wanted, as these changes don't affect the bug fix)
- Before:
As you can see the dates on the right don't have this bounding box which is clickable, and the boxes also went out of the visible area at the bottom.
- After:
Now every date has a bounding box that is clickable and no …

Fix google pixel month view

---

.github/workflows/holiday-generator/main.js

- Fixed wrong date generating in holiday generator (as reported in https://github.com/FossifyOrg/Calendar/pull/173).
- Now, regardless of the timezone where the script is run, it should always generate and read dates in UTC.
Not a screenshot, but here is a ZIP with three ICS files generated by the generator now. I've run it in GMT+1 and there are three different countries in three entirely different timezones - USA (probably ET which is GMT-5), Poland (GMT+1) and Australia (likely AEST which is GMT+10).
[holidays.zip](https://github.com/FossifyOrg/Calendar/files/14619112/holidays.zip).
As you can see, common holidays like Easter or Christmas are on the same day. I've imported them to Fossify Calendar and all were on the proper date, but I haven't changed the timezone of my phone to any …

[Holiday generator] Generate all holidays in UTC

---

app/src/main/kotlin/org/fossify/calendar/models/Event.kt

- Fix calculation of events repeating every X weeks. The previous implementation was broken in some time zones (see [#408](https://github.com/FossifyOrg/Calendar/issues/408) for details).
- Fixes #408
This PR hard-codes the start of the week to be Monday, to match the previous behaviour. Ideally this should be configurable (I added a TODO comment with notes).
Like the previous implementation, the new code uses the default time zone, ignoring the event's time zone. This is a bug and should be fixed, but will probably require significant changes so I did not attempt to do it. I suspect that's the root cause of #165.
Code review comment for existing code: The method takes a parameter `startTimes: LongSparseArray<Long>` in which it does a lookup by the event ID. I don't see any reason to pass …

Fix calculation of events repeating every X weeks

---

app/src/main/kotlin/org/fossify/calendar/helpers/IcsImporter.kt

- Handle escaped semicolons in ICS title and description
This converts text like `Święto Państwowe\; Święto Pracy` to `Święto Państwowe; Święto Pracy`.

Handle escaped semicolons

---

.github/workflows/holiday-generator/config.js

For some unknown reason, sometimes, in some timezones, events like the "New Year's Day" are missing because their start date is 01/01/1970. This quick fix resolves this issue at least for holidays.

Bump fixed date holiday start year to 1980

---

app/src/main/kotlin/org/fossify/calendar/activities/TaskActivity.kt

- Set "Mark completed" background color to primary
- Fixes #357

Apply proper color to "Mark completed" button background

---

app/src/main/kotlin/org/fossify/calendar/helpers/CalDAVHelper.kt

Previously the app modified the event colors for proper contrast ratio directly at synchronization meaning the original event colors were never saved in the app's DB. This is not necessary because the app already handles contrast ratio at the UI level. 
- This might be the reason for https://github.com/FossifyOrg/Calendar/issues/202 though I couldn't reproduce it.
- See also:
- https://github.com/FossifyOrg/Calendar/issues/188
- https://github.com/FossifyOrg/Calendar/pull/421#issuecomment-2600966222

Remove CalDAV event color modification

---

app/src/main/kotlin/org/fossify/calendar/adapters/QuickFilterEventTypeAdapter.kt

- Long press feature added in #314 isn't reverting event types that aren't shown on the quick filter bar. 
- This PR fixes it - on the second long press it reverts the filtering according to the filter popup, not according to the quick filter bar.
- Before:
https://github.com/user-attachments/assets/f3144c84-23da-464b-b3e2-1e26229ffee7
- After:
https://github.com/user-attachments/assets/662d4b22-f990-449c-9b7d-2ef5753c3ec1

Fixed reverting old filtering on quick filter long press

---

app/src/main/kotlin/org/fossify/calendar/helpers/IcsImporter.kt

- Updated IcsImporter.kt to apply local timezone to events with timestamps not ending in Z (UTC time)
- Fixes #262

Add default timezone to IcsImporter for timestamps not ending in Z (UTC)

---

app/src/main/kotlin/org/fossify/calendar/activities/MainActivity.kt

Re submit PR #224, all credits to @TristanDonze.
I cannot do a build right now, but I can more than happily test a beta build if needed (and update the PR with any necessary changes if required, of course).
- Removed code related to a hard limit (1970) for private events;
- Add proper handling of private events with dates without year.
- Please refer to #224 
- Fixes #196

Fix calendar handling of pre-1970 birthdates

---

.github/workflows/holiday-generator/config.js

- Bangladesh is in the supported country list of `date-holidays` library but it was not included in our holiday-generator config.

Add Bangladesh to holiday-generator config

---

app/src/main/res/layout/activity_event.xml

Adjusted the anchor for `event_access_level_divider` from `event_access_level_image` to `event_access_level`.
This prevents views positioned below the access level section from jumping to the top when the access level section is hidden.
- Not tracked. Caused by: https://github.com/FossifyOrg/Calendar/pull/490

fix: use direct anchor for access level divider

---

.github/dependabot.yml
.github/workflows/holiday-generator/.gitignore
.github/workflows/holiday-generator/package-lock.json

- Added `.github/workflows/holiday-generator/package-lock.json`. It was left out intentionally, but adding it now to use dependabot as a sensor for new date-holidays releases
- Added Dependabot section for npm
**Future:** Maybe rig the generator to run when date-holidays is updated by dependabot.

chore: add package-lock.json for holiday generator

---

CHANGELOG.md
app/src/main/kotlin/org/fossify/calendar/extensions/Context.kt
app/src/main/kotlin/org/fossify/calendar/receivers/NotificationReceiver.kt

Closes #732
When I decline an invitation to a meeting, a reminder that it's starting is a bit irrelevant and confusing. I think it makes sense to exclude these from notifications, mirroring the behavior of the Google Calendar app.
_No UI changes_

fix: avoid notifying for declined events

---

CHANGELOG.md
app/src/main/kotlin/org/fossify/calendar/helpers/CalDAVHelper.kt

- When fetching CalDAV events, the app will now treat `null` status as confirmed. Android defaults to tentative in this case, but that isn't desirable as per #761.
- Closes http://github.com/FossifyOrg/Calendar/issues/761

fix: default to "Confirmed" when event status is missing or null

---

CHANGELOG.md
app/src/main/kotlin/org/fossify/calendar/activities/EventActivity.kt
app/src/main/kotlin/org/fossify/calendar/activities/TaskActivity.kt

Applied the same fix as https://github.com/FossifyOrg/Contacts/pull/362 in both event and task editors. Some edits are still being discarded due to https://github.com/FossifyOrg/Calendar/issues/49, which I will address in another PR soon.
- Back navigation using the arrow button after editing events/tasks
- Closes https://github.com/FossifyOrg/Calendar/issues/803

fix: prevent silent discard of event/task edits

---

CHANGELOG.md
app/src/main/kotlin/org/fossify/calendar/activities/EventActivity.kt
app/src/main/kotlin/org/fossify/calendar/activities/TaskActivity.kt

1. Updated the `isEventChanged()` function to check for:
- Repeat limit (recurrence end)
- Attendees
- Availability (free/busy)
- Access level (private/public/confidential)
- Event status (confirmed/tentative/cancelled)
2. Updated the `isTaskChanged()` function  to check for:
- Repeat limit (recurrence end)
The issue also mentioned the timezone field, but that seems to already work properly.
Tested discarding:
- Closes https://github.com/FossifyOrg/Calendar/issues/49

fix: check all fields for unsaved changes on back press
